### ISSUE TITLE
Crash With Sodium

### ISSUE THREAD

**Issue by serioos** [Nosrick/crock-pot-mod#24] opened 2024-03-10 15:08 UTC
I placed the crock pot on the campfire and then when I right clicked it, it instantly crashed with this screen:

![2024-03-10_18 30 54](https://github.com/Nosrick/crock-pot-mod/assets/93765296/aa256663-737b-4fd2-b60b-ca64064d369f)

I looked in the log and found this error too:

https://pastebin.com/Ty1R2j5T

**Game and mod version:**

Minecraft 1.20.1 Fabric

crockpot-1.14.0+1.20.1.jar

sodium-fabric-0.5.8+mc1.20.1.jar

**Comment by Nosrick** [comment] 2024-03-11 22:17
Looks like this is a duplicate of #22, but on a different version!
I'll get to updating to 1.14.1 on other versions, and I'll try to have them out later this week.

**Comment by Nosrick** [comment] 2024-03-13 08:41
Alright, that should be the fix uploaded for 1.20.1!
I'll maybe port it back to 1.19.2 if anyone cares, but we'll see if a report comes in.

**Closed as completed by Nosrick** 2024-03-13 08:41 UTC

**Comment by serioos** [comment] 2024-03-13 08:49
Thank you so much. ❤
